package com.example.YashToolBackEnd.customer.service.impl;

import com.example.YashToolBackEnd.common.exception.BusinessException;
import com.example.YashToolBackEnd.common.exception.ResourceNotFoundException;
import com.example.YashToolBackEnd.customer.dto.CustomerRequest;
import com.example.YashToolBackEnd.customer.dto.CustomerResponse;
import com.example.YashToolBackEnd.customer.entity.Customer;
import com.example.YashToolBackEnd.customer.repository.CustomerRepository;
import com.example.YashToolBackEnd.customer.service.CustomerService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;


@Service
@RequiredArgsConstructor
public class CustomerServiceImpl implements CustomerService {

    // Repository used to interact with the database
    // Injected via constructor (generated by @RequiredArgsConstructor)
    private final CustomerRepository customerRepository;


    // Creates a new customer.
    // Mobile number must be unique among active (isDeleted=false) customers
    // Email must be unique among active (isDeleted=false) customers
    @Override
    public CustomerResponse createCustomer(CustomerRequest request) {

        // Check if mobile already exists for an active customer
        customerRepository.findByMobileNumberAndIsDeletedFalse(request.getMobileNumber())
                .ifPresent(c ->{throw new BusinessException("Mobile already exists");});
        // Check if email already exists for an active customer
        customerRepository.findByEmailAndIsDeletedFalse(request.getEmail())
                .ifPresent(c -> {throw new BusinessException("Email already exists");});

        // Build the Customer entity from request DTO
        Customer customer = Customer.builder()
                .companyName(request.getCompanyName())
                .customerName(request.getCustomerName())
                .legalEntity(request.getLegalEntity())
                .businessType(request.getBusinessType())
                .mobileNumber(request.getMobileNumber())
                .email(request.getEmail())
                .billingAddress(request.getBillingAddress())
                .deliveryAddress(request.getDeliveryAddress())
                .gstNumber(request.getGstNumber())
                .status("ACTIVE") // Default status
                .build();

        // Save the new customer and return the response DTO
        return map(customerRepository.save(customer));
    }


    // Updates an existing customer (only if not deleted).
    @Override
    public CustomerResponse updateCustomer(Long customerId, CustomerRequest request) {
        // Fetch customer by ID and ensure it's not soft-deleted
        Customer customer = customerRepository.findById(customerId)
                .filter(c-> !c.getIsDeleted())
                .orElseThrow(()-> new ResourceNotFoundException("Customer not found"));

        // Update fields
        customer.setCompanyName(request.getCompanyName());
        customer.setCustomerName(request.getCustomerName());
        customer.setLegalEntity(request.getLegalEntity());
        customer.setBusinessType(request.getBusinessType());
        customer.setMobileNumber(request.getMobileNumber());
        customer.setEmail(request.getEmail());
        customer.setBillingAddress(request.getBillingAddress());
        customer.setDeliveryAddress(request.getDeliveryAddress());
        customer.setGstNumber(request.getGstNumber());

        // Persist changes and return mapped response
        return map(customerRepository.save(customer));
    }


    // Retrieves a customer by ID (only if not deleted).
    @Override
    public CustomerResponse getCustomerById(Long customerId) {
        Customer customer = customerRepository.findById(customerId)
                .filter(c-> !c.getIsDeleted())
                .orElseThrow(()-> new ResourceNotFoundException("customer not found"));
        return map(customer);



    }

    // Retrieves all customers that are not soft-deleted.
    @Override
    public List<CustomerResponse> getAllCustomers() {
        return customerRepository.findAllByIsDeletedFalse()
                .stream()
                .map(this::map)
                .collect(Collectors.toList());
    }

    // Simple mapper method to convert entity to DTO
    private CustomerResponse map(Customer customer) {
        if (customer == null) {
            return null;
        }
        return CustomerResponse.builder()
                .id(customer.getId())
                .companyName(customer.getCompanyName())
                .customerName(customer.getCustomerName())
                .legalEntity(customer.getLegalEntity())
                .businessType(customer.getBusinessType())
                .mobileNumber(customer.getMobileNumber())
                .email(customer.getEmail())
                .billingAddress(customer.getBillingAddress())
                .deliveryAddress(customer.getDeliveryAddress())
                .gstNumber(customer.getGstNumber())
                .status(customer.getStatus())
                .build();
    }
}
