-- V1: Core auth and master-data tables
-- Target DB: PostgreSQL

CREATE TABLE role (
    id UUID PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    CONSTRAINT chk_role_name
        CHECK (name IN ('ADMIN', 'SALES', 'DESIGN', 'STORE', 'FINANCE', 'PRODUCTION', 'CA', 'QUALITY'))
);

CREATE TABLE users (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_role (
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE RESTRICT
);

CREATE TABLE audit_log (
    id UUID PRIMARY KEY,
    user_id UUID,
    action VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_audit_log_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE raw_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL UNIQUE,
    rate DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE coatings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    coating_type VARCHAR(50) NOT NULL,
    rate DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT chk_coatings_coating_type
        CHECK (coating_type IN ('HELICA', 'ALCRONA', 'VICIOUS_BLACK', 'VICIOUS_BROWN'))
);

CREATE INDEX idx_users_deleted ON users (deleted);
CREATE INDEX idx_audit_log_user_id ON audit_log (user_id);
CREATE INDEX idx_raw_materials_is_deleted ON raw_materials (is_deleted);
CREATE INDEX idx_coatings_is_deleted ON coatings (is_deleted);

