-- ============================================================
-- V1: Full Database Initialization
-- Target DB: PostgreSQL
-- Hibernate 7 compatible - includes all required sequences
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- SEQUENCES for BIGINT auto-generated IDs
-- Hibernate 7 uses GenerationType.AUTO = SEQUENCE by default
-- increment by 50 matches Hibernate default pooled optimizer
-- ============================================================

CREATE SEQUENCE enquiry_items_seq       START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE new_tool_specs_seq      START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE resharpening_specs_seq  START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE reforming_specs_seq     START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE coatings_seq            START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE raw_materials_seq       START WITH 1 INCREMENT BY 50;

-- ============================================================
-- AUTH: role table
-- Entity: Role.java
-- ID: UUID GenerationType.UUID
-- ============================================================

CREATE TABLE role (
                      id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
                      name        VARCHAR(50)  NOT NULL UNIQUE,
                      description VARCHAR(255)
);

-- ============================================================
-- AUTH: users table
-- Entity: User.java
-- ID: UUID GenerationType.UUID
-- ============================================================

CREATE TABLE users (
                       id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
                       name       VARCHAR(255) NOT NULL,
                       email      VARCHAR(255) NOT NULL UNIQUE,
                       password   VARCHAR(255) NOT NULL,
                       phone      VARCHAR(255) NOT NULL,
                       enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
                       deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
                       created_at TIMESTAMP
);

-- ============================================================
-- AUTH: user_role join table
-- Entity: User.java @JoinTable(name = "user_role")
-- ============================================================

CREATE TABLE user_role (
                           user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                           role_id UUID NOT NULL REFERENCES role(id)  ON DELETE CASCADE,
                           PRIMARY KEY (user_id, role_id)
);

-- ============================================================
-- AUTH: audit_log table
-- Entity: AuditLog.java
-- ID: UUID @GeneratedValue (no strategy = AUTO = UUID for UUID type)
-- ============================================================

CREATE TABLE audit_log (
                           id        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
                           user_id   UUID,
                           action    VARCHAR(255) NOT NULL,
                           timestamp TIMESTAMP
);

-- ============================================================
-- AUTH: refresh_tokens table
-- Entity: RefreshToken.java
-- ============================================================

CREATE TABLE refresh_tokens (
                                id          UUID      PRIMARY KEY DEFAULT gen_random_uuid(),
                                user_id     UUID      NOT NULL,
                                token       TEXT      NOT NULL UNIQUE,
                                expiry_date TIMESTAMP NOT NULL,
                                revoked     BOOLEAN   DEFAULT FALSE,
                                created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT fk_refresh_tokens_user
                                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_token   ON refresh_tokens(token);

-- ============================================================
-- MASTER: coatings table
-- Entity: Coating.java
-- ID: Long GenerationType.IDENTITY
-- But Hibernate 7 AUTO uses sequence - using IDENTITY here
-- ============================================================

CREATE TABLE coatings (
                          id           BIGINT           PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          name         VARCHAR(255)     NOT NULL,
                          coating_type VARCHAR(50)      NOT NULL,
                          rate         DOUBLE PRECISION NOT NULL,
                          active       BOOLEAN          NOT NULL
);

-- ============================================================
-- MASTER: raw_materials table
-- Entity: RawMaterial.java
-- ID: Long GenerationType.IDENTITY
-- ============================================================

CREATE TABLE raw_materials (
                               id     BIGINT           PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                               name   VARCHAR(255)     NOT NULL UNIQUE,
                               rate   DOUBLE PRECISION NOT NULL,
                               active BOOLEAN          NOT NULL DEFAULT TRUE
);

-- ============================================================
-- CUSTOMER: customers table
-- Entity: Customer.java extends AuditableEntity extends BaseEntity
-- ID: UUID GenerationType.UUID
-- ============================================================

CREATE TABLE customers (
                           id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
                           created_at       TIMESTAMP,
                           updated_at       TIMESTAMP,
                           created_by       VARCHAR(255),
                           updated_by       VARCHAR(255),
                           is_deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
                           company_name     VARCHAR(255) NOT NULL,
                           customer_name    VARCHAR(255) NOT NULL,
                           legal_entity     VARCHAR(255) NOT NULL,
                           business_type    VARCHAR(255) NOT NULL,
                           mobile_number    VARCHAR(15)  NOT NULL,
                           email            VARCHAR(50)  NOT NULL,
                           billing_address  VARCHAR(255) NOT NULL,
                           delivery_address VARCHAR(255) NOT NULL,
                           gst_number       VARCHAR(20),
                           status           VARCHAR(20)  NOT NULL,
                           CONSTRAINT uk_customers_mobile_number UNIQUE (mobile_number),
                           CONSTRAINT uk_customers_email         UNIQUE (email),
                           CONSTRAINT chk_customers_status
                               CHECK (status IN ('ACTIVE','INACTIVE','SUSPENDED','PENDING','DELETED'))
);

-- ============================================================
-- ENQUIRY: enquiries table
-- Entity: Enquiry.java extends AuditableEntity extends BaseEntity
-- ID: UUID GenerationType.UUID
-- ============================================================

CREATE TABLE enquiries (
                           id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
                           created_at  TIMESTAMP,
                           updated_at  TIMESTAMP,
                           created_by  VARCHAR(255),
                           updated_by  VARCHAR(255),
                           enquiry_no  VARCHAR(255) NOT NULL UNIQUE,
                           customer_id UUID         NOT NULL,
                           is_urgent   BOOLEAN      NOT NULL DEFAULT FALSE,
                           status      VARCHAR(20),
                           remarks     VARCHAR(255),
                           CONSTRAINT fk_enquiries_customer
                               FOREIGN KEY (customer_id) REFERENCES customers(id),
                           CONSTRAINT chk_enquiries_status
                               CHECK (status IN ('CREATED','QUOTED','CLOSED'))
);

-- ============================================================
-- ENQUIRY: enquiry_items table
-- Entity: EnquiryItem.java
-- ID: Long @GeneratedValue (AUTO) → uses enquiry_items_seq
-- ============================================================

CREATE TABLE enquiry_items (
                               id         BIGINT       PRIMARY KEY DEFAULT nextval('enquiry_items_seq'),
                               enquiry_id UUID,
                               order_type VARCHAR(30),
                               tool_name  VARCHAR(255),
                               is_trial   BOOLEAN,
                               quantity   INTEGER,
                               remarks    VARCHAR(255),
                               CONSTRAINT fk_enquiry_items_enquiry
                                   FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE,
                               CONSTRAINT chk_enquiry_items_order_type
                                   CHECK (order_type IN (
                                                         'NEW_TOOL','new_tool',
                                                         'RESHARPENING','resharpening',
                                                         'REFORMING','reforming'
                                       ))
);

-- ============================================================
-- ENQUIRY: new_tool_specs table
-- Entity: NewToolSpecs.java
-- ID: Long GenerationType.IDENTITY → uses new_tool_specs_seq
-- ============================================================

CREATE TABLE new_tool_specs (
                                id              BIGINT           PRIMARY KEY DEFAULT nextval('new_tool_specs_seq'),
                                enquiry_item_id BIGINT           NOT NULL UNIQUE,
                                has_coating     BOOLEAN          NOT NULL,
                                coating_id      BIGINT,
                                raw_material_id BIGINT           NOT NULL,
                                diameter        DOUBLE PRECISION NOT NULL,
                                flute_length    DOUBLE PRECISION NOT NULL,
                                shank_diameter  DOUBLE PRECISION NOT NULL,
                                overall_length  DOUBLE PRECISION NOT NULL,
                                CONSTRAINT fk_new_tool_specs_enquiry_item
                                    FOREIGN KEY (enquiry_item_id) REFERENCES enquiry_items(id) ON DELETE CASCADE,
                                CONSTRAINT fk_new_tool_specs_coating
                                    FOREIGN KEY (coating_id) REFERENCES coatings(id),
                                CONSTRAINT fk_new_tool_specs_raw_material
                                    FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id)
);

-- ============================================================
-- ENQUIRY: resharpening_specs table
-- Entity: ResharpeningSpecs.java
-- ID: Long @GeneratedValue (AUTO) → uses resharpening_specs_seq
-- ============================================================

CREATE TABLE resharpening_specs (
                                    id                BIGINT      PRIMARY KEY DEFAULT nextval('resharpening_specs_seq'),
                                    enquiry_item_id   BIGINT      UNIQUE,
                                    resharpening_type VARCHAR(20),
                                    has_coating       BOOLEAN     NOT NULL,
                                    coating_id        BIGINT,
                                    CONSTRAINT fk_resharpening_specs_enquiry_item
                                        FOREIGN KEY (enquiry_item_id) REFERENCES enquiry_items(id) ON DELETE CASCADE,
                                    CONSTRAINT fk_resharpening_specs_coating
                                        FOREIGN KEY (coating_id) REFERENCES coatings(id),
                                    CONSTRAINT chk_resharpening_type
                                        CHECK (resharpening_type IN ('PRIMARY','SECONDARY','FULL'))
);

-- ============================================================
-- ENQUIRY: reforming_specs table
-- Entity: ReformingSpecs.java
-- ID: Long @GeneratedValue (AUTO) → uses reforming_specs_seq
-- ============================================================

CREATE TABLE reforming_specs (
                                 id              BIGINT           PRIMARY KEY DEFAULT nextval('reforming_specs_seq'),
                                 enquiry_item_id BIGINT           UNIQUE,
                                 has_coating     BOOLEAN          NOT NULL,
                                 coating_id      BIGINT,
                                 flute_length    DOUBLE PRECISION,
                                 CONSTRAINT fk_reforming_specs_enquiry_item
                                     FOREIGN KEY (enquiry_item_id) REFERENCES enquiry_items(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_reforming_specs_coating
                                     FOREIGN KEY (coating_id) REFERENCES coatings(id)
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_customers_status         ON customers          (status);
CREATE INDEX idx_customers_is_deleted     ON customers          (is_deleted);
CREATE INDEX idx_enquiries_customer_id    ON enquiries          (customer_id);
CREATE INDEX idx_enquiries_status         ON enquiries          (status);
CREATE INDEX idx_enquiry_items_enquiry    ON enquiry_items      (enquiry_id);
CREATE INDEX idx_new_tool_coating         ON new_tool_specs     (coating_id);
CREATE INDEX idx_new_tool_raw_material    ON new_tool_specs     (raw_material_id);
CREATE INDEX idx_resharpening_coating     ON resharpening_specs (coating_id);
CREATE INDEX idx_reforming_coating        ON reforming_specs    (coating_id);

-- ============================================================
-- SEED DATA
-- ============================================================

INSERT INTO role (name, description) VALUES
                                         ('ROLE_ADMIN', 'Administrator with full access'),
                                         ('ROLE_SALES', 'Sales team member'),
                                         ('ROLE_USER',  'Regular user');