-- ============================================================
-- V2: Enhanced Database Schema - Enquiry Management System
-- PostgreSQL 14+ | UUID Support | Production Ready
-- Author: YashTools Dev Team
-- Version: 2.0
-- Date: 2024
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- ROLE TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS role (
                                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
    );

-- ============================================================
-- USERS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
                                     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- ============================================================
-- USER ROLE MAPPING
-- ============================================================

CREATE TABLE IF NOT EXISTS user_role (
                                         user_id UUID NOT NULL,
                                         role_id UUID NOT NULL,

                                         PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_role_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_user_role_role
    FOREIGN KEY (role_id)
    REFERENCES role(id)
    ON DELETE CASCADE
    );

   CREATE TABLE IF NOT EXISTS refresh_tokens (
       id UUID PRIMARY KEY,
       token VARCHAR(255) NOT NULL UNIQUE,
       user_id UUID NOT NULL,
       expiry_date TIMESTAMP NOT NULL,
       revoked BOOLEAN NOT NULL DEFAULT FALSE,
       created_at TIMESTAMP NOT NULL,
       CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
   );

   CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id);
   CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON refresh_tokens(token);


-- ============================================================
-- AUDIT LOG TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS audit_log (
                                         id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    action VARCHAR(255) NOT NULL,
    entity_name VARCHAR(255),
    entity_id VARCHAR(255),
    description TEXT,
    ip_address VARCHAR(100),
    user_agent TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE SET NULL
    );

-- ============================================================
-- COATINGS MASTER
-- ============================================================

CREATE TABLE IF NOT EXISTS coatings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL,
    coating_type VARCHAR(50) NOT NULL,
    rate DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_coating_type CHECK (
                                          coating_type IN ('HELICA', 'ALCRONA', 'VICIOUS_BLACK', 'VICIOUS_BROWN')
    )
    );

-- ============================================================
-- RAW MATERIAL MASTER
-- ============================================================

CREATE TABLE IF NOT EXISTS raw_materials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(150) NOT NULL UNIQUE,
    rate DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deactivated_at TIMESTAMP
);

-- ============================================================
-- CUSTOMERS
-- ============================================================

CREATE TABLE IF NOT EXISTS customers (
                                         id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Audit fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),

    -- Soft delete
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    -- Business fields
    company_name VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    legal_entity VARCHAR(255) NOT NULL,
    business_type VARCHAR(255) NOT NULL,

    -- Contact details
    mobile_number VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,

    -- Address
    billing_address VARCHAR(255) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,

    -- Tax
    gst_number VARCHAR(20),

    -- Status
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT chk_customer_status CHECK (
                                             status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', 'DELETED')
    )
    );

-- ============================================================
-- ENQUIRIES (UPDATED)
-- ============================================================

CREATE TABLE IF NOT EXISTS enquiries (
                                         id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Audit fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),

    -- Business fields
    enquiry_no VARCHAR(20) NOT NULL UNIQUE,
    customer_id UUID NOT NULL,
    is_urgent BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED',

    -- Foreign key
    CONSTRAINT fk_enquiry_customer
    FOREIGN KEY (customer_id)
    REFERENCES customers(id)
    ON DELETE RESTRICT,

    -- Status constraint
    CONSTRAINT chk_enquiry_status CHECK (
                                            status IN ('CREATED', 'UNDER_REVIEW', 'QUOTED', 'ACCEPTED', 'CLOSED')
    )
    );

-- ============================================================
-- ENQUIRY ITEMS (UPDATED - REMOVED sample_provided, remarks moved here only)
-- ============================================================

CREATE TABLE IF NOT EXISTS enquiry_items (
                                             id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key
    enquiry_id UUID NOT NULL,

    -- Business fields
    order_type VARCHAR(20) NOT NULL,
    tool_name VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    trial BOOLEAN NOT NULL DEFAULT FALSE,

    -- Optional fields
    remarks TEXT,
    drawing_reference VARCHAR(500),

    -- Foreign key constraint
    CONSTRAINT fk_item_enquiry
    FOREIGN KEY (enquiry_id)
    REFERENCES enquiries(id)
    ON DELETE CASCADE,

    -- Order type constraint
    CONSTRAINT chk_order_type CHECK (
                                        order_type IN ('NEW_TOOL', 'RESHARPENING', 'REFORMING')
    )
    );

-- ============================================================
-- NEW TOOL SPECS (UPDATED - Added Material Type/Grade, Boolean Coating)
-- ============================================================

CREATE TABLE IF NOT EXISTS new_tool_specs (
                                              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key
    enquiry_item_id UUID NOT NULL UNIQUE,

    -- Material specifications (NEW)
    material_type VARCHAR(30) NOT NULL,
    material_grade VARCHAR(30) NOT NULL,

    -- Coating specifications (UPDATED)
    coating_required BOOLEAN NOT NULL DEFAULT FALSE,
    coating_type VARCHAR(30),

    -- Dimensional specifications (FIXED: DOUBLE PRECISION to match Java Double)
    diameter DOUBLE PRECISION NOT NULL CHECK (diameter > 0),
    flute_length DOUBLE PRECISION NOT NULL CHECK (flute_length > 0),
    shank_diameter DOUBLE PRECISION NOT NULL CHECK (shank_diameter > 0),
    overall_length DOUBLE PRECISION NOT NULL CHECK (overall_length > 0),

    -- Technical notes
    technical_notes TEXT,

    -- Foreign key constraint
    CONSTRAINT fk_new_tool_item
    FOREIGN KEY (enquiry_item_id)
    REFERENCES enquiry_items(id)
    ON DELETE CASCADE,

    -- Material type constraint
    CONSTRAINT chk_material_type CHECK (
                                           material_type IN ('HSS', 'CARBIDE', 'COBALT_HSS', 'PM_HSS', 'TOOL_STEEL')
    ),

    -- Material grade constraint
    CONSTRAINT chk_material_grade CHECK (
                                            material_grade IN ('M2', 'M35', 'M42', 'K10', 'K20', 'K30', 'O1', 'A2', 'D2', 'ASP23', 'ASP30')
    ),

    -- Coating type constraint
    CONSTRAINT chk_new_tool_coating_type CHECK (
                                                   coating_type IS NULL OR coating_type IN ('HELICA', 'ALCRONA', 'VICIOUS_BLACK', 'VICIOUS_BROWN')
    )
    );

-- ============================================================
-- RESHARPENING SPECS (UPDATED - Boolean Coating)
-- ============================================================

CREATE TABLE IF NOT EXISTS resharpening_specs (
                                                  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key
    enquiry_item_id UUID NOT NULL UNIQUE,

    -- Resharpening specifications
    resharpening_type VARCHAR(20) NOT NULL,

    -- Coating specifications (UPDATED)
    coating_required BOOLEAN NOT NULL DEFAULT FALSE,
    coating_type VARCHAR(30),

    -- Technical notes
    technical_notes TEXT,

    -- Foreign key constraint
    CONSTRAINT fk_resharpening_item
    FOREIGN KEY (enquiry_item_id)
    REFERENCES enquiry_items(id)
    ON DELETE CASCADE,

    -- Resharpening type constraint
    CONSTRAINT chk_resharpening_type CHECK (
                                               resharpening_type IN ('PRIMARY', 'SECONDARY', 'FULL')
    ),

    -- Coating type constraint
    CONSTRAINT chk_resharpening_coating_type CHECK (
                                                       coating_type IS NULL OR coating_type IN ('HELICA', 'ALCRONA', 'VICIOUS_BLACK', 'VICIOUS_BROWN')
    )
    );

-- ============================================================
-- REFORMING SPECS (UPDATED - Boolean Coating)
-- ============================================================

CREATE TABLE IF NOT EXISTS reforming_specs (
                                               id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key
    enquiry_item_id UUID NOT NULL UNIQUE,

    -- Coating specifications (UPDATED)
    coating_required BOOLEAN NOT NULL DEFAULT FALSE,
    coating_type VARCHAR(30),

    -- Dimensional specifications (FIXED: DOUBLE PRECISION to match Java Double)
    flute_length DOUBLE PRECISION NOT NULL CHECK (flute_length > 0),

    -- Technical notes
    technical_notes TEXT,

    -- Foreign key constraint
    CONSTRAINT fk_reforming_item
    FOREIGN KEY (enquiry_item_id)
    REFERENCES enquiry_items(id)
    ON DELETE CASCADE,

    -- Coating type constraint
    CONSTRAINT chk_reforming_coating_type CHECK (
                                                    coating_type IS NULL OR coating_type IN ('HELICA', 'ALCRONA', 'VICIOUS_BLACK', 'VICIOUS_BROWN')
    )
    );

-- ============================================================
-- PERFORMANCE INDEXES
-- ============================================================

-- Customer indexes
CREATE INDEX IF NOT EXISTS idx_customers_status ON customers(status);
CREATE INDEX IF NOT EXISTS idx_customers_deleted ON customers(is_deleted);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_customers_mobile ON customers(mobile_number);

-- Enquiry indexes
CREATE INDEX IF NOT EXISTS idx_enquiry_no ON enquiries(enquiry_no);
CREATE INDEX IF NOT EXISTS idx_enquiry_status ON enquiries(status);
CREATE INDEX IF NOT EXISTS idx_enquiry_customer ON enquiries(customer_id);
CREATE INDEX IF NOT EXISTS idx_enquiry_created ON enquiries(created_at);
CREATE INDEX IF NOT EXISTS idx_enquiry_urgent ON enquiries(is_urgent) WHERE is_urgent = TRUE;

-- Enquiry item indexes
CREATE INDEX IF NOT EXISTS idx_item_enquiry ON enquiry_items(enquiry_id);
CREATE INDEX IF NOT EXISTS idx_item_order_type ON enquiry_items(order_type);
CREATE INDEX IF NOT EXISTS idx_item_trial ON enquiry_items(trial) WHERE trial = TRUE;

-- Audit log indexes
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_log(action);

-- Coating and raw material indexes
CREATE INDEX IF NOT EXISTS idx_coatings_active ON coatings(active) WHERE active = TRUE;
CREATE INDEX IF NOT EXISTS idx_raw_materials_active ON raw_materials(active) WHERE active = TRUE;

-- ============================================================
-- TABLE COMMENTS (Documentation)
-- ============================================================

COMMENT ON TABLE enquiries IS 'Customer enquiry requests for tool orders';
COMMENT ON TABLE enquiry_items IS 'Individual items within an enquiry';
COMMENT ON TABLE new_tool_specs IS 'Specifications for new tool manufacturing (material + coating)';
COMMENT ON TABLE reforming_specs IS 'Specifications for tool reforming services';
COMMENT ON TABLE resharpening_specs IS 'Specifications for tool resharpening services';

-- Column comments
COMMENT ON COLUMN enquiries.enquiry_no IS 'System-generated unique identifier (Format: ENQ-YYYY-####)';
COMMENT ON COLUMN enquiries.is_urgent IS 'Priority flag for expedited processing';
COMMENT ON COLUMN enquiry_items.trial IS 'Trial order flag (max quantity: 1)';
COMMENT ON COLUMN new_tool_specs.coating_required IS 'If true, coating_type must be specified';
COMMENT ON COLUMN new_tool_specs.material_type IS 'Base material (HSS, Carbide, etc.)';
COMMENT ON COLUMN new_tool_specs.material_grade IS 'Material grade (M2, M35, K10, etc.)';
COMMENT ON COLUMN reforming_specs.coating_required IS 'If true, coating_type must be specified';
COMMENT ON COLUMN resharpening_specs.coating_required IS 'If true, coating_type must be specified';

-- ============================================================
-- DEFAULT ROLES
-- ============================================================

INSERT INTO role (name, description)
VALUES
    ('ROLE_ADMIN', 'Administrator with full access'),
    ('ROLE_SALES', 'Sales team member'),
    ('ROLE_USER', 'Regular user'),
    ('ROLE_PRODUCTION', 'Production team member'),
    ('ROLE_FINANCE', 'Finance team member'),
    ('ROLE_STORE', 'Store/Inventory manager'),
    ('ROLE_QUALITY', 'Quality assurance team'),
    ('ROLE_MANAGER', 'Department manager'),
    ('ROLE_CA', 'Chartered Accountant')
    ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- SAMPLE DATA (Optional - for testing)
-- ============================================================

-- Insert sample coating types
INSERT INTO coatings (name, coating_type, rate, active)
VALUES
    ('HELICA Coating', 'HELICA', 150.00, TRUE),
    ('ALCRONA Coating', 'ALCRONA', 200.00, TRUE),
    ('VICIOUS BLACK Coating', 'VICIOUS_BLACK', 180.00, TRUE),
    ('VICIOUS BROWN Coating', 'VICIOUS_BROWN', 180.00, TRUE)
    ON CONFLICT DO NOTHING;

-- Insert sample raw materials
INSERT INTO raw_materials (name, rate, active)
VALUES
    ('HSS M2', 500.00, TRUE),
    ('HSS M35', 650.00, TRUE),
    ('HSS M42', 800.00, TRUE),
    ('Carbide K10', 1200.00, TRUE),
    ('Carbide K20', 1000.00, TRUE),
    ('Carbide K30', 900.00, TRUE)
    ON CONFLICT DO NOTHING;

-- ============================================================
-- VIEWS (Optional - for reporting)
-- ============================================================

-- View: Active enquiries with customer details
CREATE OR REPLACE VIEW v_active_enquiries AS
SELECT
    e.id AS enquiry_id,
    e.enquiry_no,
    e.created_at,
    e.is_urgent,
    e.status,
    c.id AS customer_id,
    c.company_name,
    c.customer_name,
    c.email,
    c.mobile_number,
    COUNT(ei.id) AS item_count,
    BOOL_OR(ei.trial) AS has_trial
FROM enquiries e
         INNER JOIN customers c ON e.customer_id = c.id
         LEFT JOIN enquiry_items ei ON e.id = ei.enquiry_id
WHERE e.status != 'CLOSED'
  AND c.is_deleted = FALSE
GROUP BY e.id, c.id;

-- View: Enquiry items with specifications summary
CREATE OR REPLACE VIEW v_enquiry_items_summary AS
SELECT
    ei.id AS item_id,
    ei.enquiry_id,
    ei.order_type,
    ei.tool_name,
    ei.quantity,
    ei.trial,
    CASE
        WHEN nts.id IS NOT NULL THEN 'NEW_TOOL'
        WHEN rs.id IS NOT NULL THEN 'RESHARPENING'
        WHEN rfs.id IS NOT NULL THEN 'REFORMING'
        ELSE 'UNKNOWN'
        END AS spec_type,
    CASE
        WHEN nts.coating_required = TRUE THEN nts.coating_type
        WHEN rs.coating_required = TRUE THEN rs.coating_type
        WHEN rfs.coating_required = TRUE THEN rfs.coating_type
        ELSE NULL
        END AS coating_type,
    nts.material_type,
    nts.material_grade
FROM enquiry_items ei
         LEFT JOIN new_tool_specs nts ON ei.id = nts.enquiry_item_id
         LEFT JOIN resharpening_specs rs ON ei.id = rs.enquiry_item_id
         LEFT JOIN reforming_specs rfs ON ei.id = rfs.enquiry_item_id;

-- ============================================================
-- FUNCTIONS (Optional - for business logic)
-- ============================================================

-- Function: Generate next enquiry number
CREATE OR REPLACE FUNCTION generate_enquiry_number()
    RETURNS VARCHAR(20) AS $$
DECLARE
current_year INTEGER;
    next_sequence INTEGER;
    last_enquiry_no VARCHAR(20);
    last_year INTEGER;
BEGIN
    current_year := EXTRACT(YEAR FROM CURRENT_DATE);

    -- Get last enquiry number
SELECT enquiry_no INTO last_enquiry_no
FROM enquiries
ORDER BY created_at DESC
    LIMIT 1;

IF last_enquiry_no IS NULL THEN
        next_sequence := 1;
ELSE
        -- Extract year and sequence from last enquiry number
        last_year := CAST(SPLIT_PART(last_enquiry_no, '-', 2) AS INTEGER);

        IF last_year = current_year THEN
            next_sequence := CAST(SPLIT_PART(last_enquiry_no, '-', 3) AS INTEGER) + 1;
ELSE
            next_sequence := 1;
END IF;
END IF;

RETURN 'ENQ-' || current_year || '-' || LPAD(next_sequence::TEXT, 4, '0');
END;
$$ LANGUAGE plpgsql;

-- Function: Check trial quantity validation
CREATE OR REPLACE FUNCTION validate_trial_quantity()
    RETURNS TRIGGER AS $$
BEGIN
    IF NEW.trial = TRUE AND NEW.quantity > 1 THEN
        RAISE EXCEPTION 'Trial quantity cannot exceed 1. Current quantity: %', NEW.quantity;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Validate trial items before insert/update
CREATE TRIGGER trg_validate_trial_quantity
    BEFORE INSERT OR UPDATE ON enquiry_items
                         FOR EACH ROW
                         EXECUTE FUNCTION validate_trial_quantity();

-- Function: Update timestamp on update
CREATE OR REPLACE FUNCTION update_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers: Auto-update timestamps
CREATE TRIGGER trg_customers_updated_at
    BEFORE UPDATE ON customers
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_enquiries_updated_at
    BEFORE UPDATE ON enquiries
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- ============================================================
-- VACUUM AND ANALYZE (Optimize after initial setup)
-- ============================================================

-- VACUUM ANALYZE;

-- ============================================================
-- END OF MIGRATION
-- ============================================================