-- ============================================================
-- V2: Labors Management Tables
-- Target DB: PostgreSQL
-- ============================================================

-- ============================================================
-- LABORS: laborers table
-- ============================================================
CREATE TABLE laborers (
    id          BIGINT           PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)     NOT NULL,
    ph_number   VARCHAR(20),
    email       VARCHAR(255),
    address     VARCHAR(500),
    labor_role  VARCHAR(50)      NOT NULL,
    wage_type   VARCHAR(50)      NOT NULL,
    daily_wage  DECIMAL(19, 2),
    piece_rate  DECIMAL(19, 2),
    hourly_rate DECIMAL(19, 2),
    is_active   BOOLEAN          DEFAULT TRUE
);

-- ============================================================
-- LABORS: attendance table
-- ============================================================
CREATE TABLE attendance (
    id                BIGINT           PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    laborer_id        BIGINT           NOT NULL REFERENCES laborers(id),
    work_date         DATE             NOT NULL,
    check_in_time     TIME,
    check_out_time    TIME,
    hours_worked      DECIMAL(10, 2),
    pieces_completed  INTEGER,
    earned_amount     DECIMAL(19, 2)   NOT NULL,
    wage_type_snapshot VARCHAR(50)      NOT NULL,
    applied_rate      DECIMAL(19, 2)   NOT NULL,
    UNIQUE(laborer_id, work_date)
);

-- ============================================================
-- LABORS: advance_transactions table
-- ============================================================
CREATE TABLE advance_transactions (
    id               BIGINT           PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    laborer_id       BIGINT           NOT NULL REFERENCES laborers(id),
    transaction_date DATE             NOT NULL,
    amount           DECIMAL(19, 2)   NOT NULL,
    transaction_type VARCHAR(50)      NOT NULL,
    notes            TEXT
);

-- ============================================================
-- LABORS: weekly_payouts table
-- ============================================================
CREATE TABLE weekly_payouts (
    id                BIGINT           PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    laborer_id        BIGINT           NOT NULL REFERENCES laborers(id),
    week_start_date   DATE             NOT NULL,
    week_end_date     DATE             NOT NULL,
    total_hours       DECIMAL(10, 2),
    gross_payout      DECIMAL(19, 2)   NOT NULL,
    advance_deduction DECIMAL(19, 2)   NOT NULL,
    net_payout        DECIMAL(19, 2)   NOT NULL,
    payment_status    VARCHAR(50)      NOT NULL,
    payment_date      DATE,
    payment_reference VARCHAR(255),
    pieces_completed  DECIMAL(19, 2),
    UNIQUE(laborer_id, week_start_date, week_end_date)
);
