-- V2: Customer and enquiry domain tables
-- Target DB: PostgreSQL

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    company_name VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    legal_entity VARCHAR(255) NOT NULL,
    business_type VARCHAR(255) NOT NULL,
    mobile_number VARCHAR(15) NOT NULL,
    email VARCHAR(50) NOT NULL,
    billing_address VARCHAR(255) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,
    gst_number VARCHAR(20),
    status VARCHAR(20) NOT NULL,
    CONSTRAINT uk_customers_mobile_number UNIQUE (mobile_number),
    CONSTRAINT uk_customers_email UNIQUE (email),
    CONSTRAINT chk_customers_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', 'DELETED'))
);

CREATE TABLE enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    enquiry_no VARCHAR(255) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    is_urgent BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20),
    remarks VARCHAR(255),
    CONSTRAINT fk_enquiries_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT chk_enquiries_status CHECK (status IN ('CREATED', 'QUOTED', 'CLOSED'))
);

CREATE TABLE enquiry_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enquiry_id BIGINT,
    order_type VARCHAR(30),
    tool_name VARCHAR(255),
    is_trial BOOLEAN,
    quantity INTEGER,
    remarks VARCHAR(255),
    CONSTRAINT fk_enquiry_items_enquiry FOREIGN KEY (enquiry_id) REFERENCES enquiries (id) ON DELETE CASCADE,
    CONSTRAINT chk_enquiry_items_order_type
        CHECK (order_type IN ('NEW_TOOL', 'new_tool', 'RESHARPENING', 'resharpening', 'REFORMING', 'reforming'))
);

CREATE TABLE new_tool_specs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enquiry_item_id BIGINT NOT NULL UNIQUE,
    has_coating BOOLEAN NOT NULL,
    coating_id BIGINT,
    raw_material_id BIGINT NOT NULL,
    diameter DOUBLE PRECISION NOT NULL,
    flute_length DOUBLE PRECISION NOT NULL,
    shank_diameter DOUBLE PRECISION NOT NULL,
    overall_length DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_new_tool_specs_enquiry_item FOREIGN KEY (enquiry_item_id) REFERENCES enquiry_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_new_tool_specs_coating FOREIGN KEY (coating_id) REFERENCES coatings (id),
    CONSTRAINT fk_new_tool_specs_raw_material FOREIGN KEY (raw_material_id) REFERENCES raw_materials (id)
);

CREATE TABLE resharpening_specs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enquiry_item_id BIGINT UNIQUE,
    resharpening_type VARCHAR(20),
    has_coating BOOLEAN NOT NULL,
    coating_id BIGINT,
    CONSTRAINT fk_resharpening_specs_enquiry_item FOREIGN KEY (enquiry_item_id) REFERENCES enquiry_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_resharpening_specs_coating FOREIGN KEY (coating_id) REFERENCES coatings (id),
    CONSTRAINT chk_resharpening_specs_type CHECK (resharpening_type IN ('PRIMARY', 'SECONDARY', 'FULL'))
);

CREATE TABLE reforming_specs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enquiry_item_id BIGINT UNIQUE,
    has_coating BOOLEAN NOT NULL,
    coating_id BIGINT,
    flute_length DOUBLE PRECISION,
    CONSTRAINT fk_reforming_specs_enquiry_item FOREIGN KEY (enquiry_item_id) REFERENCES enquiry_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_reforming_specs_coating FOREIGN KEY (coating_id) REFERENCES coatings (id)
);

CREATE INDEX idx_customers_is_deleted ON customers (is_deleted);
CREATE INDEX idx_customers_status ON customers (status);
CREATE INDEX idx_enquiries_customer_id ON enquiries (customer_id);
CREATE INDEX idx_enquiries_status ON enquiries (status);
CREATE INDEX idx_enquiry_items_enquiry_id ON enquiry_items (enquiry_id);
CREATE INDEX idx_new_tool_specs_coating_id ON new_tool_specs (coating_id);
CREATE INDEX idx_new_tool_specs_raw_material_id ON new_tool_specs (raw_material_id);
CREATE INDEX idx_resharpening_specs_coating_id ON resharpening_specs (coating_id);
CREATE INDEX idx_reforming_specs_coating_id ON reforming_specs (coating_id);

