-- ============================================================
-- V6: Rate Chart Module Tables
-- PostgreSQL 14+
-- ============================================================

CREATE TABLE IF NOT EXISTS hyperion_rod_net_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item VARCHAR(255) NOT NULL,
    k40uf_h10f DOUBLE PRECISION NOT NULL,
    am70_dm80 DOUBLE PRECISION NOT NULL,
    pn90 DOUBLE PRECISION NOT NULL,
    gp10_k10f DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_hyperion_rod_net_price_item UNIQUE (item)
);

CREATE TABLE IF NOT EXISTS hyperion_coolant_hole_rod_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255) NOT NULL,
    item VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_coolant_hole_category_item UNIQUE (category, item)
);
